config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "static_pages#home"

  resources :users
  resources :treasures do
    resources :theories
  end

  get "/recent", to: "theories#recent"

  get "/auth/github/callback", to: "sessions#omniauth"
  get "/signin", to: "sessions#new"
  post "/signin", to: "sessions#create"
  delete "/signout", to: "sessions#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/theory.rb
class Theory < ApplicationRecord
	belongs_to :user, foreign_key: :user_id, optional: true
	belongs_to :treasure

	validates :name, presence: true
	validates :description, presence: true
	validates :description, uniqueness: true, on: :create

	scope :success, -> {where(success: true)}

	def self.recent_theories
		order('created_at desc').limit(3)
	end

end

app/models/treasure.rb
class Treasure < ApplicationRecord
	has_many :theories, :dependent => :destroy
	has_many :users, through: :theories
	accepts_nested_attributes_for :theories, allow_destroy: true

	belongs_to :creating_user, foreign_key: :user_id, optional: true

	validates :name, presence: true
	validates :name, uniqueness: true, on: :create

	def theories_attributes=(theory_attributes)
		theory_attributes.values.each do |atts|
			theory = Theory.find_or_create_by(atts)
			self.theories << theory
		end
	end


end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password

	has_many :theories
	has_many :created_treasure
	has_many :treasures, through: :theories

	validates :username && :email, presence: true
	validates :username, uniqueness: true, on: :create

	def self.find_or_create_by_oa(auth_hash)
		where(:email => auth_hash["info"]["email"]).first_or_create do |u|
			u.password = SecureRandom.hex
		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception

	helper_method :current_user

	def logged_in?
		!!current_user
	end

	def current_user
		@current_user ||= User.find(session[:user_id]) if session[:user_id]
	end

	def logged_in_req
		redirect_to signin_path unless logged_in?
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :logged_in_req, except: [:new, :create, :home, :omniauth]

  def new
    @user = User.new
    @users = User.all
  end
  def create
    @user = User.find_by(username: params[:user][:username])
    if @user && @user.authenticate(params[:user][:password])
      session[:user_id] = @user.id
      redirect_to user_path(@user), :notice => "Signed In!"
    else
      redirect_to signin_path, :notice => "Unable to sign you in, please try again."
    end
  end

  def omniauth
    if auth_hash = request.env["omniauth.auth"]
      user = User.find_or_create_by_oa(auth_hash)
      session[:user_id] = user.id
      redirect_to root_url, :notice => "Signed In!"
    else
      redirect_to root_url, :notice => "Unable to sign you in, please try again."
    end
  end

  def destroy
  	session.clear
  	redirect_to root_url, :notice => "Logged Out"
  end

  private

  def auth
    request.env["omniauth.auth"]
  end


end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/theories_controller.rb
class TheoriesController < ApplicationController

  # THEORY CREATION
  def new
    treasure
    @theory = Theory.new
  end
  def create
    treasure
    @theory = @treasure.theories.build(theory_params)
    @theory.user_id = current_user.id
    if @theory.save
      redirect_to @treasure, notice: "Theory was successfully saved"
    else
      render :new
    end
  end

  # THEORY EDIT
  def edit
    theory
    treasure
  end
  def update
    treasure
    theory.update(theory_params)
    if theory.save
      redirect_to treasure_path(@treasure), notice: "Theory was successfully updated"
    else
      render :edit
    end
  end

  # THEORY DESTROY
  def destroy
    treasure
    theory.destroy
    redirect_to treasure_path(@treasure), notice: "Theory was successfully destroyed"
  end

  # THEORY LIST - RECENT 3
  def recent
    @theories = Theory.recent_theories
  end

  private

  def theory
    @theory = Theory.find_by(id: params[:id])
  end

  def treasure
    @treasure = Treasure.find_by(id: params[:treasure_id])
  end

  def theory_params
    params.require(:theory).permit(:name, :description, :issues, :success, :prove_date, :creator, :treasure_id, :user_id)
  end

end

app/controllers/treasures_controller.rb
class TreasuresController < ApplicationController

  def index
    @treasures = Treasure.all
    theory
  end

  def show
    treasure
    theory
    @theories = Theory.all
  end

  def new
    @treasure = Treasure.new
    @treasure.theories.build
  end
  def create
    @treasure = Treasure.new(treasure_params)
    @treasure.user_id = current_user.id
    if @treasure.save
      redirect_to @treasure, notice: "Treasure was successfully saved"
    else
      render :new
    end
  end

  def edit
    treasure
  end
  def update
    treasure
    if treasure.update(treasure_params)
      redirect_to treasure_path, notice: "Treasure was successfully updated"
    else
      render :edit
    end
  end

  def destroy
    treasure.destroy
    redirect_to treasures_url, notice: "Treasure was successfully destroyed"
  end

  private

  def treasure
    @treasure = Treasure.find_by(id: params[:id])
  end

  def theory
    @theory = Theory.find_by(id: params[:id])
  end

  def treasure_params
    params.require(:treasure).permit(:name, :description,
      theories_attributes: [:name, :description, :issues, :success, :prove_date, :treasure_id, :user_id]
    )
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :user, only: [:show, :edit, :update, :destroy]

  def show
  end

  def new
    @user = User.new
  end
  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user), notice: "Welcome to Ouro!"
    else
      render :new
    end
  end

  def edit
  end
  def update
    if user.update(user_params)
      redirect_to user_path(@user), notice: "User has been successfully updated!"
    else
      render :edit
    end
  end

  def destroy
    user.clear
    redirect_to user_path
  end

  private

  def user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:username,:email, :password, :admin)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/theories_helper.rb
module TheoriesHelper
end

app/helpers/treasures_helper.rb
module TreasuresHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ouro Rails Project</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <ul class="nav navbar-nav">
        <% if current_user %>
          <li><%= link_to "My Profile", user_path(current_user) %></li>
          <li><%= link_to "Treasures", treasures_path %></li>
          <li><%= link_to "Log Out", signout_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign Up", new_user_path %></li>
          <li><%= link_to "Sign In", signin_path %></li>
          <li><%= link_to "Sign in with Github", "/auth/github" %></li>
        <% end %>
      </ul>
    </div>

    <div class="container" role="main">
     <%= yield %>
    </div>
  </body>
</html>

app/views/static_pages/home.html.erb
<h1><%= "Welcome to Ouro!"%></h1>

app/views/theories/_form.html.erb
<%= form_for [@treasure, @theory] do |f| %>
	<% if @theory.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(@theory.errors.count, "error") %> prohibited this theory from being saved:</h2>
			<ul>
				<% @theory.errors.full_messages.each do |message| %>
					<li><%= message %></li>
				<% end %>
			</ul>
		</div>
	<% end %>


	<div class="form-group">
		<%= f.label :name %><br><%= f.text_field :name, class: "form-control" %>
	</div>

	<div class="form-group">
		<%= f.label :description %><br><%= f.text_field :description, class: "form-control" %>
	</div>

	<div class="form-group">
		<%= f.label :issues %><br><%= f.text_field :issues, class: "form-control" %>
	</div>

	<div class="form-group">
		<%= f.label :success %><br><%= f.check_box :success, class: "form-control" %>
	</div>

	<div class="form-group">
		<%= f.label :prove_date %><br><%= f.date_field :prove_date, class: "form-control" %>
	</div><br>

		<%= f.hidden_field :user_id, :value => current_user.id %>

	<div class="actions">
		<%= f.submit "Add Theory" %>
	</div>

<% end %>

app/views/theories/edit.html.erb
<h1>Edit Theory</h1>

<%= render 'form' %>

app/views/theories/new.html.erb
<h1>New Theory for <%= @treasure.name %></h1>

<%= render 'form' %>

app/views/theories/recent.html.erb
<h1>Most Recent Theories</h1>

<!-- list 3 theories and link to treasure show page -->
<table class="box" align="center">
	<tr>
		<th>Theory Name</th>
		<th>Created By</th>
		<th>Treasure Name</th>
	</tr>

	<% @theories.each do |t| %>
		<tr>
			<td><%= t.name %></td>
			<td><%= t.user.username %></td>
			<td><%= link_to "#{t.treasure.name}", treasure_path(t.treasure) %></td>
		</tr>
	<% end %>
</table><br>

app/views/treasures/_form.html.erb
<%= form_for @treasure do |f| %>
	<% if @treasure.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(@treasure.errors.count, "error") %> prohibited this treasure from being saved:</h2>
			<ul>
				<% @treasure.errors.full_messages.each do |message| %>
					<li><%= message %></li>
				<% end %>
			</ul>
		</div>
	<% end %>

	<%= f.label :name %><br><%= f.text_field :name, class: "form-control" %><br>
	<%= f.label :description %><br><%= f.text_area :description, class: "form-control" %><br><br>

	<%= f.fields_for :theories, @treasure.theories.build do |theory| %>
		<%= theory.label :theory_name %><br><%= theory.text_field :name %><br>
		<%= theory.label :theory_description %><br><%= theory.text_area :description %><br>
		<%= theory.label :theory_issues %><br><%= theory.text_field :issues %><br>
		<%= theory.label :theory_success %><br><%= theory.check_box :success %><br>
		<%= theory.label :theory_prove_date %><br><%= theory.date_field :prove_date %><br>

		<%= theory.hidden_field :user_id, :value => current_user.id %>
	<% end %><br>

	<%= f.submit class: "btn btn-primary" %>

<% end %>

app/views/treasures/_form_update.html.erb
<%= form_for @treasure do |f| %>
	<% if @treasure.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(@treasure.errors.count, "error") %> prohibited this treasure from being saved:</h2>
			<ul>
				<% @treasure.errors.full_messages.each do |message| %>
					<li><%= message %></li>
				<% end %>
			</ul>
		</div>
	<% end %>

	<%= f.label :name %><br><%= f.text_field :name, class: "form-control" %><br>
	<%= f.label :description %><br><%= f.text_area :description, class: "form-control" %><br><br>

	<%= f.submit class: "btn btn-primary" %>

<% end %>

app/views/treasures/edit.html.erb
<h1>Edit Treasure</h1>

<%= render 'form_update' %><br>

app/views/treasures/index.html.erb
<h1>List of Treasures</h1>

<table class="table" align="center">
  <thead>
    <tr><th colspan="2"></th></tr>
  </thead>
  <tbody>
    <tr>
      <td><strong>Name</strong></td>
      <td><strong>Description</strong></td>
    </tr>

    <% @treasures.each do |treasure| %>
      <tr>
        <td><%= treasure.name %></td>
        <td><%= treasure.description %></td>

        <% if current_user.admin %>
          <td><%= link_to "Show #{treasure.name}", treasure_path(treasure) %></td>
          <td><%= link_to "Delete #{treasure.name}", treasure_path(treasure), method: :delete, data: { confirm: "Are you sure you want to delete #{treasure.name}?" } %></td>
        <% else %>
          <td><%= link_to "Find #{treasure.name}", treasure_path(treasure) %></td>
        <% end %>

      </tr><br>
    <% end %>
  </tbody>
</table><br>

<p><%= link_to "New Treasure", new_treasure_path %> | <%= link_to "Most Recent Theories", "/recent" %></p>

app/views/treasures/new.html.erb
<h1>Create New Treasure</h1>

<%= render 'form' %><br>

app/views/treasures/show.html.erb
<p id="notice"><%= notice %></p>

<div class="center">
  <div class="info">
    <p><strong>Name</strong><br><%= @treasure.name %></p>
    <p><strong>Description</strong><br><%= @treasure.description %></p>

    <table class="box" align="center">
      <tr>
        <th>Theory Name</th>
        <th>Theory Description</th>
        <th>Theory Issues</th>
        <th>Theory Success?</th>
        <th>Theory Prove Date</th>
        <th>Created By</th>
        <th>Edit</th>
        <th>Delete</th>
      </tr>
      <% @treasure.theories.success.each do %>
        <h3 style="color: red; font-style: italic;">Mystery Solved!</h3>
      <% end %>
      <% @treasure.theories.each do |t| %>
        <tr>
          <td><%= t.name %></td>
          <td><%= t.description %></td>
          <td><%= t.issues %></td>
          <td><%= t.success %></td>
          <td><%= t.prove_date %></td>
          <td><%= t.user.username %></td>
          <td><%= link_to "Edit #{t.name}", [:edit, @treasure, t] %></td>
          <td><%= link_to "Delete #{t.name}", [@treasure, t], method: :delete, data: { confirm: "Are you sure you want to delete #{t.name}?" } %></td>

        </tr>
      <% end %>
    </table><br>

    <%= link_to 'Edit', [:edit, @treasure] %> | <%= link_to 'Create Theory', new_treasure_theory_path(@treasure.id) %>
  </div>
</div>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
	<% if @user.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
			<ul style="list-style-type:none;">
				<% @user.errors.full_messages.each do |message| %>
					<li><%= message %></li>
				<% end %>
			</ul>
		</div>
	<% end %>

	<div class="form-group">
		<%= f.label :username %><br><%= f.text_field :username, class: "form-control" %>
	</div><br>

	<div class="form-group">
		<%= f.label :email %><br><%= f.text_field :email, class: "form-control" %>
	</div><br>

	<div class="form-group">
		<%= f.label :password %><br><%= f.password_field :password, class: "form-control" %>
	</div><br>

	<div class="form-group">
	<%= f.label :are_you_an_admin? %><%= f.check_box :admin %>
	</div><br>

	<div class="actions">
		<%= f.submit class: "btn btn-primary" %><br>
	</div><br>

<% end %>

app/views/users/edit.html.erb
<h1>Edit User</h1>

<%= render 'form' %><br>

<%= link_to 'Show', @user %>

app/views/users/new.html.erb
<h1>Create New User</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<p id="notice"><h1><%= notice %></h1></p>

<% if @message %>
	<div class="center alert">
		<p><%= @message %></p>
	</div>
<% end %>

<div class="center">
	<div class="info">
		<% if @user.admin %>
			<p><strong>ADMIN</strong></p>
		<% end %><br>
		<p><strong>NAME: </strong><%= @user.username %></p>
		<p><strong>EMAIL: </strong><%= @user.email %></p><br>
		<p><%= link_to 'Edit', edit_user_path(@user) %></p>
	</div>
</div>

app/views/users/signin.html.erb
<h1>Sign In with Existing Account</h1>

<%= form_for @user, url: "/users/login" do |f| %>
	<div class="field">
		<%= f.label :name, "Select your name" %><br><%= f.collection_select(:id, @users, :id, :name) %>
	</div>
	<div class="actions"><%= f.submit "Sign In" %></div><br>

<% end %>